### ISSUE TITLE
Discussion on #features/workbook/events

### ISSUE THREAD

**Issue by ccsrvs** [GrapeCity/spreadjs-demos#2]
When filling out data into a cell block, then changing the selection and coming back to the original cell, when pressing delete (while not in cell edit mode), no event seems to fire or is logged. I also don't see on your events descriptions page which may handle this. 

What event handles this situation?

---
#### features/workbook/events

**Comment by Kevin-GrapeCity** [comment]
Hello,

This demo will only fire events that it has bound in code.  In the case of the delete key for deleting cell data, that is a range-level event, so simply binding to the RangedChanged event will fire when the user presses the delete key on a cell: https://www.grapecity.com/spreadjs/api/classes/GC.Spread.Sheets.Events#rangechanged
