### ISSUE TITLE
Discussion on #features/cells/drop-downs/date-time-picker

### ISSUE THREAD

**Issue by vuongpq562k** [GrapeCity/spreadjs-demos#7]
I have created a date picker cell button with the same configuration as you (showTime = false). However, it is not working as expected. The cell calendar still displays both date and time, regardless of any format changes I make. Please consider my issue.

![showTime false is not work](https://github.com/user-attachments/assets/7e9781c5-8d95-4bc8-a251-abdbc1549b35)

---
#### features/cells/drop-downs/date-time-picker

**Comment by Kevin-GrapeCity** [comment]
Hello,

It looks like that is indeed just an issue with the demo, and our developers are working on fixing it.  Thank you for bringing this to our attention!

Regards,
Kevin
